# fly.toml app configuration file generated for gerenciador-tarefas-api on 2025-03-20T12:37:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gerenciador-tarefas-api'
primary_region = 'gig'

[build]
  dockerfile = 'Dockerfile'

[env]
  SERVER_PORT = '8080'
  SPRING_PROFILES_ACTIVE = 'prod'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
