# fly.toml app configuration file generated for usuarioapi-young-brook-4416 on 2025-03-20T12:54:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'usuarioapi-young-brook-4416'
primary_region = 'gru'

[build]

[[mounts]]
  source = 'tmp'
  destination = '/tmp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1



