[phases.setup]
nixPkgs = ['nixpkgs.jdk21_headless', 'nixpkgs.maven']

[phases.build]
cmds = ['./mvnw clean package -DskipTests']
dependsOn = ['setup']

[start]
cmd = 'java -jar -Dspring.profiles.active=prod target/Gerenciador-de-Tarefas-0.0.1-SNAPSHOT.jar' 