spring:
  application:
    name: gerenciamentoTarefa
  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
    username: postgres.azkqdfdhlzqatkakgavt
    password: "kazito10@"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    basic:
      enabled: false

server:
  port: 8080
